# Generated by Django 4.1.7 on 2023-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercaderias', '0002_rename_proovedores_proveedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='Cuit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compras',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Cuit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='Cuit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
